## TODO: Remember that the radius parameter is not set here ... Change back to [1, 5]
batch_size: 32  # 27
epoch: 200
learning_rate: 0.00005  # 0.00005
lr_gamma: 0.85
lr_step: 10
lambda_lf: 0.5  # how to weight emd (lambda=0) vs cross entropy (lambda=1)
gpu: 0
optimizer: Adam
weight_decay: 0.0001
model:
  nneighbor: 16
  nblocks: 4  # Number of transformer-transition blocks in backbone
  transformer_dim: 256
  name: Hengshuang
# Which features to use
features_to_create:
  use_label: true  # class label
  use_jde: true  # joint differential entropy
  use_sde: true  # separate differential entropy
  use_sd: true  # sinkhorn divergence
  use_c: true # covisibility weight
  use_s: false  # static weight
  use_cj: true  # joint cardinality ratio
  use_cs: true  # separate cardinality ratio
features_to_use:
  use_label: true  # class label
  use_jde: true  # joint differential entropy
  use_sde: true  # separate differential entropy
  use_sd: true  # sinkhorn divergence
  use_c: true  # covisibility weight
  use_s: false  # static weight
  use_cj: true  # joint cardinality ratio
  use_cs: true  # separate cardinality ratio
xyz_features:
  use_xyz: false
  use_z: true
  use_norm_xyz: true
aug:
  norm_xyz: true
  dropout: true
  scale: true
  shift: true
batch_size_feature_extraction: 128
# Covisibility parameters (see Katz and Tal)
covisibility:
  inversion_kernel: "spherical_flipping"  # spherical_flipping is the other choice
  gamma: -0.0001  # Parameter for the exponential inversion kernel
  hpr_radius: 2.75  # Parameter for the spherical flipping method
# Data setup
num_point: 2048  # 512
re_use_data: true  # Set to true if only running training and no feature extraction
n_scenes: 335  # 335
n_samples_per_scene: 10 # 10  
dataset: 'v1.0-trainval'  # 'v1.0-trainval'
data_folder: '/home/luddi824/thesis/PCAC/data/nuscenes/'
feature_folder: '/home/luddi824/thesis/PCAC/data/PCAC_data/best_settings_2'  # TODO: Set by new user ...
downsample_factor: 1 # Make sure that the point cloud is not so downsampled that num_point does not exist
train_ratio: 0.60  # The test ratio automatically becomes 1 - train_ratio - val_ratio
val_ratio: 0.15  # Simply set to 0 if validation set in not needed
model_identifier: none

# Rerun settings, enables us to rerun after a crash, without rerunning everything
rerun_crash: false
scenes_finished: 256  # How many scenes we managed to extract before crash
time_gone: 19.10  # Time spent, so we can keep track of time left
# If error is displayed, reduce scenes_finished, so that we do not look at test data ...
rerun_only_test: false
# Perturbation settings
perturb_settings:
  n_classes: 10
  r_bin: 0.01
  t_bin: 0.1
  class_distribution: uniform

# Plot settings
ablation: false
plot_train_acc: false
# Sensor settings (HDL-32E)
sensor_settings:
  vertical_angular_res: 0.02327481098473072  # [rad]. Corresponds to 1.333548387 degrees
  horizontal_angular_res: 0.005817764173314432  # [rad]. Corresponds to 1/3 degrees
  scan_frequency: 20  # [Hz]. Can be changed between 5-20 Hz, but the nuScenes data is 20 Hz.
  lower_vert_fov: -0.5352925062179565  # [rad]. Lower vertical field of view. Corresponds to -30.67 degrees.
  upper_vert_fov: 0.18622663617134094  # [rad]. Upper vertical field of view. Corresponds to 10.67 degrees.
  max_distance: 100  # [m]
  vert_channels: 32
  hori_channels: 1080
# Neighborhood settings
neighborhood:
  rmin: 0.5
  rmax: 7.5
  alpha_scale: 5
  k: adaptive  # adaptive, joint
# Differential entropy settings
diff_entropy:
  log_epsilon: -18.0
  E_reject: 0.20  # does not matter when we work point-wise
# Sinkhorn divergence settings
sinkhorn_div:
  p: 2
  blur: 0.05
# Preprocessing
preprocessing:
  T_close: 1.5  # remove all points within 1.5 meters
  preprocess: true  # (bool): whether to preprocess the point cloud or not

# Choose classifier
classifier: FACT  # CorAl

# Other settings
verbose: false  # (bool): If True, print additional information.
debug: false
#load_model_path: /home/luddi824/thesis/PCAC/outputs/2023-08-13/17-39-23/best_model.pth
load_model_path: false
running_iterations: 6  # This requires a setup in the train_cls.py file. Otherwise, set this to 1.