batch_size: 20  # 27
epoch: 40 # 500, TODO: Could reduce training time by not running test(), maybe decrease time by 40%
learning_rate: 0.00005 # 0.0005
gpu: 0
optimizer: Adam
weight_decay: 0.0001
normal: true
model:
  nneighbor: 16
  nblocks: 4  # Number of transformer-transition blocks in backbone
  transformer_dim: 128  # TODO: Investigate if I could decrease this ... Should save lots of memory
  name: Hengshuang
# Which features to use (we always use xyz)
features_to_create:
  use_label: true  # class label
  use_jde: true  # joint differential entropy
  use_sde: true  # separate differential entropy
  use_sd: true  # sinkhorn divergence
  use_c: true # covisibility weight
  use_s: false  # static weight
  use_cj: true  # joint cardinality ratio
  use_cs: true  # separate cardinality ratio
features_to_use:
  use_label: true  # class label
  use_jde: true  # joint differential entropy
  use_sde: true  # separate differential entropy
  use_sd: true  # sinkhorn divergence
  use_c: true  # covisibility weight
  use_s: false  # static weight
  use_cj: true  # joint cardinality ratio
  use_cs: true  # separate cardinality ratio
batch_size_feature_extraction: 128
# Covisibility parameters (see Katz and Tal)
covisibilty:
  inversion_kernel: "exponential"  # spherical_flipping is the other choice
  gamma: -0.0001   # Parameter for the exponential inversion kernel
  hpr_radius: 3.25  # Parameter for the spherical flipping method
# Data setup
num_point: 2048  # 512
re_use_data: false
n_scenes: 100
n_samples_per_scene: 1
dataset: 'v1.0-trainval'  # 'v1.0-trainval'
feature_folder: '/home/luddi824/thesis/PCAC/data/PCAC_data'  # TODO: Set by new user ...
downsample_factor: 8 # Make sure that the point cloud is not so downsampled that num_point does not exist
train_ratio: 0.60  # The test ratio automatically becomes 1 - train_ratio - val_ratio
val_ratio: 0.15  # Simply set to 0 if validation set in not needed
# Rerun settings, enables us to rerun after a crash, without rerunning everything
rerun_crash: false
scenes_finished: 256  # How many scenes we managed to extract before crash
time_gone: 19.10  # Time spent, so we can keep track of time left
# If error is displayed, reduce scenes_finished, so that we do not look at test data ...
# Perturbation settings
# perturb_settings:
#   n_classes: 10
#   r_bin: 0.01
#   t_bin: 0.1
#   class_distribution: uniform
perturb_settings:
  n_classes: 2
  r_bin: 0.1
  t_bin: 1
  class_distribution: uniform
# Other settings
debug: false
#load_model_path: "/home/luddi824/thesis/PCAC/outputs/2023-08-04/15-07-23/best_model.pth"
load_model_path: false
# Plot settings
ablation: false
plot_train_acc: true